---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N16"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.jp10.hana.ondemand.com"
    cfOrg: "lcap_jp"
    cfSpace: "dev"
    cfCredentialsId: "my-credential-cf"
    uiVeri5ExecuteTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    cfApiEndpoint: ""
    cfOrg: ""
    cfSpace: ""
    cfCredentialsId: ""
    tmsUpload: false
steps:
  mtaBuild:
    dockerImage: "devxci/mbtci-java11-node16@sha256:caba6f24a7abc2be53199ca892de143ad6dd26de36cc7dabbd19230afbfd38d7"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: ""
    credentialsId: ""
